version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Wpf"
          command: |
            msbuild ./LapsRemote/LapsRemote.Skia.Wpf.Host/LapsRemote.Skia.Wpf.Host.csproj -property:Configuration=Release 
      - run:
          name: "Build Uwp"
          command: |
            msbuild ./LapsRemote/LapsRemote.UWP/LapsRemote.UWP.csproj /p:Configuration=Release
workflows:
  build:
    jobs:
      - build